// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	am "backed/internal/handler/am"
	auth "backed/internal/handler/auth"
	project "backed/internal/handler/project"
	team "backed/internal/handler/team"
	user "backed/internal/handler/user"
	"backed/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/am/api/detail/save",
				Handler: am.ApiDetailSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/am/api/tree/page",
				Handler: am.ApiTreeQueryPageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/email/login",
				Handler: auth.AuthEmailLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/email/register",
				Handler: auth.AuthEmailCodeRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/email/sendCode",
				Handler: auth.SendEmailCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/getQRCode",
				Handler: auth.GetQRCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/project/copy",
				Handler: project.ProjectCopyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/create",
				Handler: project.ProjectCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/project/delete/:id",
				Handler: project.ProjectDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/page",
				Handler: project.ProjectQueryPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/update",
				Handler: project.ProjectUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/team/create",
				Handler: team.TeamCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/team/delete/:id",
				Handler: team.TeamDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/team/detail/:id",
				Handler: team.TeamDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/team/member/invite",
				Handler: team.TeamMemberInviteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/team/member/page",
				Handler: team.TeamMemberQueryPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/team/page",
				Handler: team.TeamQueryPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/team/settings/detail/:id",
				Handler: team.TeamSettingsDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/team/update",
				Handler: team.TeamUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/team/user/search",
				Handler: team.TeamUserSearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/actions",
				Handler: user.UserActionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/page",
				Handler: user.UserQueryPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/profile",
				Handler: user.UserProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/setPassword",
				Handler: user.UserSetPasswordHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
