// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	apiapi "github.com/qianjisantech/easypost/backed/internal/handler//api/api"
	"github.com/qianjisantech/easypost/backed/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/page",
				Handler: apiapi.ApiQueryPageHandler(serverCtx),
			},
		},
	)
}
