apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easypost-app-ingress
spec:
  rules:
    - http:  # 去掉host字段
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: easypost-app
                port:
                  number: 8080